name: libmpv library (macOS - ARM64)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Installing mpv
        run: |
          brew install mpv
      - name: Copying the library
        run: |
          cp /opt/homebrew/Cellar/mpv/*/lib/libmpv.2.dylib libmpv-2.dylib
      - name: Uploading the library
        uses: actions/upload-artifact@v4
        with:
          name: "libmpv library"
          path: libmpv-2.dylib
